/* Aufgabenliste: Informatik-Biber 2025 (alle 37 Aufgaben) und ausgewaehlte Aufgaben der Hefte 2020-2024.
   Jede Aufgabe hat Thema, Heftjahr, Heftseite und ihre Schwierigkeit laut Heft je Altersgruppe
   (Klassenstufen 3-4, 5-6, 7-8, 9-10, 11-13).
   d (0..1) ist die relative Position in der Aufgabenliste ihres Heftes (Seite 6: nach ungefaehr steigender
   Schwierigkeit): 0 = leichteste, 1 = schwerste Aufgabe des Heftes. Die Liste hier ist nach d sortiert und bildet die
   gemeinsame Schwierigkeitsskala fuer das adaptive Training. */
window.BIBER_TASKS = [
  { id: 'fingerfarben', title: 'Fingerfarben', topic: 'Systeme, Neuronale Netze, Diffusionsmodell', page: 37, year: 2025, d: 0, groups: {'3-4': 'einfach'} },
  { id: 'passendesfach24', title: 'Passendes Fach?', topic: 'Modellierung, Datenstrukturen, Hashing', page: 44, year: 2024, d: 0.0, groups: {'3-4': 'einfach'} },
  { id: 'aepfel23', title: 'Äpfel halbieren', topic: 'Modellierung, Datenstrukturen, Liste', page: 9, year: 2023, d: 0.0, groups: {'3-4': 'einfach'} },
  { id: 'kinderbuecher22', title: 'Kinder lieben Bücher', topic: 'Modellierung, Datenbanken', page: 35, year: 2022, d: 0.0, groups: {'3-4': 'einfach', '5-6': 'einfach'} },
  { id: 'kugeln21', title: 'Kugeln ordnen', topic: 'Algorithmen, Lösungssuche', page: 34, year: 2021, d: 0, groups: {'3-4': 'schwer', '7-8': 'einfach'} },
  { id: 'zumbahnhof20', title: 'Zum Bahnhof!', topic: 'Programmieren, Fehler', page: 64, year: 2020, d: 0, groups: {'3-4': 'einfach'} },
  { id: 'flugzeuge', title: 'Flugzeuge', topic: 'Algorithmen, Optimierung, Scheduling', page: 38, year: 2025, d: 0.0278, groups: {'3-4': 'einfach', '5-6': 'einfach'} },
  { id: 'zeichnung24', title: 'Zeichnung', topic: 'Systeme, Roboter, Computer Vision', page: 76, year: 2024, d: 0.0278, groups: {'5-6': 'einfach'} },
  { id: 'zweige20', title: 'Zweige', topic: 'Algorithmen, Sortieren, Vergleiche', page: 65, year: 2020, d: 0.0286, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'foto23', title: 'Foto', topic: 'Modellierung, Datenstrukturen, (zyklisch) verkettete Liste', page: 28, year: 2023, d: 0.0303, groups: {'5-6': 'einfach'} },
  { id: 'bienenwaben22', title: 'Bienenwaben', topic: 'Algorithmen, Lösungssuche, Heuristik', page: 17, year: 2022, d: 0.0312, groups: {'3-4': 'mittel'} },
  { id: 'sporthemd21', title: 'Sporthemd', topic: 'Modellierung, Datenbanken, Attribute', page: 50, year: 2021, d: 0.0323, groups: {'3-4': 'einfach'} },
  { id: 'hivobu', title: 'Hivobu', topic: 'Programmierung, Syntax, Postfix-Notation', page: 42, year: 2025, d: 0.0556, groups: {'3-4': 'schwer', '5-6': 'einfach'} },
  { id: 'impark24', title: 'Im Park', topic: 'Modellierung, Datenstrukturen, Stack', page: 35, year: 2024, d: 0.0556, groups: {'3-4': 'einfach'} },
  { id: 'teddybaer20', title: 'Teddybär', topic: 'Modellierung, Fehlerkorrektur', page: 58, year: 2020, d: 0.0571, groups: {'3-4': 'einfach'} },
  { id: 'baum23', title: 'Ein besonderer Baum', topic: 'Programmieren, Grundbausteine, Variablen', page: 25, year: 2023, d: 0.0606, groups: {'3-4': 'schwer', '5-6': 'mittel'} },
  { id: 'bonbon22', title: 'Bonbon-Spender', topic: 'Modellierung, Datenstrukturen, Stack', page: 19, year: 2022, d: 0.0625, groups: {'3-4': 'einfach'} },
  { id: 'stempelbild21', title: 'Stempelbild', topic: 'Modellierung, Mathematik, Ordnung', page: 51, year: 2021, d: 0.0645, groups: {'3-4': 'einfach'} },
  { id: 'bauklotze1', title: 'Bauklötze 1', topic: 'Programmierung, Grundbausteine, Sequenz', page: 9, year: 2025, d: 0.0833, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'pizza24', title: 'Pizza-Party', topic: 'Algorithmen, Optimierung, Bewertungsfunktion', page: 47, year: 2024, d: 0.0833, groups: {'3-4': 'schwer', '7-8': 'einfach'} },
  { id: 'buntestrasse20', title: 'Bunte Straße', topic: 'Modellierung, Graphen, Färbung', page: 21, year: 2020, d: 0.0857, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'blumenstrauss23', title: 'Blumenstrauß', topic: 'Modellierung, Algorithmen, Programmablaufplan', page: 15, year: 2023, d: 0.0909, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'burger22', title: 'Biber-Burger', topic: 'Algorithmen, Lösungssuche, Constraint Satisfaction', page: 13, year: 2022, d: 0.0938, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'geschenka21', title: 'Lieblingsgeschenk a', topic: 'Algorithmen, Optimierung, Rank-Maximal Matching', page: 36, year: 2021, d: 0.0968, groups: {'3-4': 'mittel', '5-6': 'einfach', '7-8': 'einfach'} },
  { id: 'obstkoerbe', title: 'Obstkörbe', topic: 'Algorithmen, Sortieren, Ordnung', page: 62, year: 2025, d: 0.1111, groups: {'3-4': 'einfach'} },
  { id: 'riccakarten124', title: 'Ricca-Karten 1', topic: 'Programmierung, Datentypen', page: 49, year: 2024, d: 0.1111, groups: {'3-4': 'einfach'} },
  { id: 'imtheater20', title: 'Im Theater', topic: 'Modellierung, Bits, Bit-Operationen, Schaltungen', page: 32, year: 2020, d: 0.1143, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'wasserland23', title: 'Wasser – Land', topic: 'Modellierung, Abstraktion, Daten', page: 62, year: 2023, d: 0.1212, groups: {'3-4': 'einfach'} },
  { id: 'herzbild22', title: 'Herzbild', topic: 'Programmieren, Anweisungen / Operationen', page: 31, year: 2022, d: 0.125, groups: {'3-4': 'schwer', '5-6': 'mittel'} },
  { id: 'bruecken21', title: 'Brückenbau', topic: 'Modellierung, Mathematik, Mengen', page: 12, year: 2021, d: 0.129, groups: {'3-4': 'einfach', '5-6': 'einfach'} },
  { id: 'nachhause', title: 'Nach Hause', topic: 'Algorithmus, Analyse, Bias', page: 60, year: 2025, d: 0.1389, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'ballon124', title: 'Ballon-Maschine 1', topic: 'Programmierung, Grundbausteine, Sequenz', page: 9, year: 2024, d: 0.1389, groups: {'3-4': 'schwer'} },
  { id: 'amschwersten20', title: 'Am schwersten', topic: 'Algorithmen, Sortieren, Topologische Sortierung', page: 7, year: 2020, d: 0.1429, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'riccas23', title: 'Riccas', topic: 'Modellierung, Logik', page: 50, year: 2023, d: 0.1515, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'ausmalbild22', title: 'Ausmalbild', topic: 'Algorithmen, Graphen, Färbung', page: 9, year: 2022, d: 0.1562, groups: {'3-4': 'einfach'} },
  { id: 'wassermuehlen21', title: 'Wassermühlen', topic: 'Modellierung, Logik, Bedingungen', page: 61, year: 2021, d: 0.1613, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'bauklotze2', title: 'Bauklötze 2', topic: 'Algorithmen, Eigenschaften, wohldefiniert', page: 11, year: 2025, d: 0.1667, groups: {'7-8': 'einfach'} },
  { id: 'faktencheck24', title: 'Faktencheck', topic: 'Modellierung, Logik, Logische Operatoren', page: 27, year: 2024, d: 0.1667, groups: {'5-6': 'schwer', '7-8': 'mittel'} },
  { id: 'ineinemzug20', title: 'In einem Zug', topic: 'Algorithmen, Graphen, Eulerscher Pfad', page: 34, year: 2020, d: 0.1714, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'saegerei23', title: 'Noahs Sägerei', topic: 'Algorithmen, Optimierung, Behälterproblem', page: 42, year: 2023, d: 0.1818, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'vertauschen22', title: 'Vertauschen', topic: 'Algorithmen, Sortieren, Vertauschungen', page: 60, year: 2022, d: 0.1875, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'geschenkb21', title: 'Lieblingsgeschenk b', topic: 'Algorithmen, Optimierung, Rank-Maximal Matching', page: 37, year: 2021, d: 0.1935, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'tagnebel', title: 'Tag im Nebel', topic: 'Algorithmen, Computergrafik, Floodfill Algorithmus', page: 74, year: 2025, d: 0.1944, groups: {'7-8': 'einfach', '9-10': 'einfach'} },
  { id: 'nebeneinander24', title: 'Nebeneinander', topic: 'Modellierung, Datenstrukturen, (doppelt verkettete) Liste', page: 41, year: 2024, d: 0.1944, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'schatzsuche20', title: 'Schatzsuche', topic: 'Programmieren, Parallelisierung, Threads, Locks', page: 50, year: 2020, d: 0.2, groups: {'5-6': 'schwer'} },
  { id: 'regenschirm23', title: 'Aylas Regenschirm', topic: 'Algorithmen, Suchen, Zeichenketten', page: 11, year: 2023, d: 0.2121, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'muttern22', title: 'Muttern und Schrauben', topic: 'Modellierung, Automaten, Kellerautomat', page: 42, year: 2022, d: 0.2188, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'zahlenmaschine', title: 'Zahlenmaschine', topic: 'Algorithmen, Sortieren, Sortiernetzwerk', page: 78, year: 2025, d: 0.2222, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'berukone24', title: 'Berukone', topic: 'Algorithmen, Lösungssuche, Backtracking', page: 19, year: 2024, d: 0.2222, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'seerosen21', title: 'Seerosen-Treff', topic: 'Algorithmen, Lösungssuche, Breiten- und Tiefensuche', page: 47, year: 2021, d: 0.2258, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'rundgang20', title: 'Rundgang', topic: 'Algorithmen, Graphen, Hamiltonkreis', page: 48, year: 2020, d: 0.2286, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'traumhaus23', title: 'Karlas Traumhaus', topic: 'Modellierung, Geodaten, Ebenen', page: 34, year: 2023, d: 0.2424, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'blaetter', title: 'Blätter im Wind', topic: 'Algorithmen, Klassifikation, Entscheidungsbaum', page: 26, year: 2025, d: 0.25, groups: {'7-8': 'einfach'} },
  { id: 'oliversrassel24', title: 'Olivers Rassel', topic: 'Modellierung, Datenstrukturen, (verkettete) Liste', page: 43, year: 2024, d: 0.25, groups: {'3-4': 'mittel'} },
  { id: 'hase22', title: 'Schildkröte und Hase', topic: 'Modellierung, Datenstrukturen, Liste', page: 48, year: 2022, d: 0.25, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'armband20', title: 'Armband', topic: 'Theoretische Informatik, Formale Sprachen, Grammatik', page: 9, year: 2020, d: 0.2571, groups: {'5-6': 'schwer', '7-8': 'einfach'} },
  { id: 'schildkroeten21', title: 'Vier Schildkröten', topic: 'Algorithmen, Graphen, Hamiltonpfad', page: 59, year: 2021, d: 0.2581, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'huete23', title: 'Neue Hüte', topic: 'Algorithmen, Sortieren, Ordnung', page: 41, year: 2023, d: 0.2727, groups: {'3-4': 'einfach'} },
  { id: 'lampe', title: 'Verrückte Lampe', topic: 'Modellierung, Logik, Operatoren', page: 76, year: 2025, d: 0.2778, groups: {'3-4': 'schwer', '5-6': 'mittel'} },
  { id: 'leuchtt24', title: 'Leuchttürme', topic: 'Modellierung, Logik, Aussagenlogik', page: 39, year: 2024, d: 0.2778, groups: {'3-4': 'einfach'} },
  { id: 'achteck22', title: 'Geheimes Achteck', topic: 'Kodierung, Verschlüsselung', page: 29, year: 2022, d: 0.2812, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'rasensprenger20', title: 'Rasensprenger', topic: 'Algorithmen, Optimierung, Partitionierung', page: 46, year: 2020, d: 0.2857, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'muenzen21', title: 'Emils Münzen', topic: 'Methodik, Abstraktion', page: 21, year: 2021, d: 0.2903, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'zoo23', title: 'Spaß im Zoo', topic: 'Algorithmen, Optimierung, Scheduling', page: 56, year: 2023, d: 0.303, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'lefty1', title: 'Lefty 1', topic: 'Systeme, Architektur, Befehlssatz', page: 50, year: 2025, d: 0.3056, groups: {'3-4': 'mittel'} },
  { id: 'riccakarten224', title: 'Ricca-Karten 2', topic: 'Programmierung, Datentypen', page: 51, year: 2024, d: 0.3056, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'nachbarn22', title: 'Lilis Nachbarn', topic: 'Modellierung, Graphen', page: 36, year: 2022, d: 0.3125, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'bienenflug20', title: 'Bienenflug', topic: 'Algorithmen, Optimierung, Dynamische Programmierung', page: 16, year: 2020, d: 0.3143, groups: {'3-4': 'einfach'} },
  { id: 'erdbeerklau21', title: 'Erdbeerklau', topic: 'Modellierung, Graphen, Cliquen', page: 23, year: 2021, d: 0.3226, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'biberholz', title: 'Biberholz', topic: 'Modellierung, Datenbanken, Abfragen', page: 19, year: 2025, d: 0.3333, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'roberta24', title: 'Robertas Roboter', topic: 'Algorithmen, Lösungssuche, Tiefensuche', page: 53, year: 2024, d: 0.3333, groups: {'3-4': 'schwer', '7-8': 'einfach'} },
  { id: 'schatzsuche23', title: 'Schatzsuche', topic: 'Modellierung, Distanzen, Manhattan-Distanz', page: 54, year: 2023, d: 0.3333, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'geschaefte20', title: 'Geschäfte', topic: 'Algorithmen, Graphen, Minimum Edge Cover', page: 29, year: 2020, d: 0.3429, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'tina22', title: 'Roboter Tina', topic: 'Systeme, Roboter, Aktoren / Sensoren', page: 44, year: 2022, d: 0.3438, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'baeumefaellen21', title: 'Bäume fällen', topic: 'Algorithmen, Sortieren, lokale Sortiertheit', page: 7, year: 2021, d: 0.3548, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'holz', title: 'Holz für den Damm', topic: 'Algorithmen, Optimierung, Teilfolge', page: 44, year: 2025, d: 0.3611, groups: {'3-4': 'schwer', '5-6': 'mittel'} },
  { id: 'zettel24', title: 'Zettel', topic: 'Systeme, Netzwerke, Peer-To-Peer', page: 77, year: 2024, d: 0.3611, groups: {'9-10': 'einfach', '11-13': 'einfach'} },
  { id: 'schatzkisten23', title: 'Schatzkisten', topic: 'Modellierung, Logik', page: 52, year: 2023, d: 0.3636, groups: {'7-8': 'einfach'} },
  { id: 'nimm20', title: 'Nim(m)', topic: 'Algorithmen, Spiele, Nim', page: 41, year: 2020, d: 0.3714, groups: {'9-10': 'schwer', '11-13': 'schwer'} },
  { id: 'fiatlux22', title: 'Fiat Lux', topic: 'Systeme, Schaltungen, Logik-Bausteine', page: 25, year: 2022, d: 0.375, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'schluesselanhaenger21', title: 'Schlüsselanhänger', topic: 'Kodierung, Kodes mit variabler Wortlänge, Morse-Code', page: 46, year: 2021, d: 0.3871, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'kerzen', title: 'Brennende Kerzen', topic: 'Algorithmen, Analyse, Verifikation', page: 31, year: 2025, d: 0.3889, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'sonnige24', title: 'Sonnige Tage', topic: 'Modellierung, Logik, Prädikatenlogik', page: 63, year: 2024, d: 0.3889, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'brunnen23', title: 'Brunnen', topic: 'Algorithmen, Graphen, (minimum distance k-)dominating sets', page: 19, year: 2023, d: 0.3939, groups: {'7-8': 'schwer', '9-10': 'mittel'} },
  { id: 'blumenkasten20', title: 'Blumenkasten', topic: 'Algorithmen, Optimierung, Optimierungsfunktion', page: 17, year: 2020, d: 0.4, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'mariaskiste22', title: 'Marias Kiste', topic: 'Algorithmen, Lösungssuche, Brute Force / Backtracking', page: 38, year: 2022, d: 0.4062, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'mehltransport', title: 'Mehltransport', topic: 'Algorithmen, Optimierung, Scheduling', page: 56, year: 2025, d: 0.4167, groups: {'9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'scott24', title: 'Scotts Armbänder', topic: 'Algorithmen, Optimierung, Dynamische Programmierung', page: 59, year: 2024, d: 0.4167, groups: {'7-8': 'schwer', '9-10': 'mittel'} },
  { id: 'ueberblick21', title: 'Überblick', topic: 'Algorithmen, Graphen, minimale Knotenüberdeckung', page: 55, year: 2021, d: 0.4194, groups: {'5-6': 'schwer', '7-8': 'mittel'} },
  { id: 'zugentladen23', title: 'Zug entladen', topic: 'Algorithmen, Sortieren, Inversion', page: 69, year: 2023, d: 0.4242, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'digitalebaeume20', title: 'Digitale Bäume', topic: 'Theoretische Informatik, Formale Sprachen, L-Systeme', page: 23, year: 2020, d: 0.4286, groups: {'11-13': 'schwer'} },
  { id: 'zahlenfolgen22', title: 'Zahlenfolgen', topic: 'Modellierung, Datenstrukturen, Array', page: 62, year: 2022, d: 0.4375, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'stammbaum', title: 'Stammbaum', topic: 'Modellierung, Mathematik, Funktionen', page: 72, year: 2025, d: 0.4444, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'roehre24', title: 'Röhre', topic: 'Modellierung, Datenstrukturen, Deque', page: 55, year: 2024, d: 0.4444, groups: {'5-6': 'einfach'} },
  { id: 'schichten21', title: 'Flüssige Schichten', topic: 'Algorithmen, Sortieren, Topologische Sortierung', page: 27, year: 2021, d: 0.4516, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'gemuesebeet23', title: 'Gemüsebeet', topic: 'Algorithmen, Lösungssuche, Backtracking', page: 30, year: 2023, d: 0.4545, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'passwoerter20', title: 'Passwörter', topic: 'Modellierung, Automaten, DEA', page: 42, year: 2020, d: 0.4571, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'stickmuster22', title: 'Stickmuster', topic: 'Programmieren, Grundbausteine, Bedingung / Wiederholung', page: 54, year: 2022, d: 0.4688, groups: {'7-8': 'einfach'} },
  { id: 'blumentoepfe', title: 'Blumentöpfe', topic: 'Algorithmen, Lösungssuche, Bottom-Up', page: 29, year: 2025, d: 0.4722, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'gnomesort24', title: 'Baustein-Maschine 1', topic: 'Algorithmen, Sortieren, Gnomesort', page: 15, year: 2024, d: 0.4722, groups: {'7-8': 'schwer'} },
  { id: 'fliesen21', title: 'Fliesenmuster', topic: 'Modellierung, Mathematik, Kachelung', page: 25, year: 2021, d: 0.4839, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'karotten23', title: 'Karotten pflanzen', topic: 'Algorithmen, Grundbausteine, Sequenz', page: 35, year: 2023, d: 0.4848, groups: {'3-4': 'schwer', '7-8': 'einfach'} },
  { id: 'tannensudoku20', title: 'Tannen-Sudoku', topic: 'Kodierung, Kompression', page: 56, year: 2020, d: 0.4857, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'bebrasien', title: 'Bebrasien', topic: 'Modellierung, Graphen', page: 13, year: 2025, d: 0.5, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'superbebras24', title: 'Superbebras', topic: 'Theoretische Informatik, Automaten, DEA', page: 67, year: 2024, d: 0.5, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'teppich22', title: 'Teppichmuster', topic: 'Programmieren / Algorithmen, Grundbausteine, Bedingung', page: 56, year: 2022, d: 0.5, groups: {'5-6': 'schwer', '7-8': 'mittel'} },
  { id: 'sierpinski20', title: 'Sierpinski-Dreieck', topic: 'Modellierung, Rekursion, Fraktale', page: 52, year: 2020, d: 0.5143, groups: {'9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'martinasdorf23', title: 'Martinas Dorf', topic: 'Modellierung, Graphen, Spannbaum', page: 39, year: 2023, d: 0.5152, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'buecherei21', title: 'Bücherei', topic: 'Modellierung, Datenstrukturen, Hashing', page: 13, year: 2021, d: 0.5161, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'seoul', title: 'Entdecke Seoul!', topic: 'Algorithmen, Graphen-Algorithmen, Tiefensuche', page: 35, year: 2025, d: 0.5278, groups: {'7-8': 'schwer'} },
  { id: 'wunderblume24', title: 'Wunderblume', topic: 'Theortische Informatik, Komplexität, Logarithmische Zeit', page: 74, year: 2024, d: 0.5278, groups: {'3-4': 'schwer', '5-6': 'mittel'} },
  { id: 'matrosenketten22', title: 'Matrosenketten', topic: 'Modellierung, Datenstrukturen, Deque', page: 40, year: 2022, d: 0.5312, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'bequemebiber20', title: 'Bequeme Biber', topic: 'Kodierung, Fehlerkorrektur, Gray Code', page: 11, year: 2020, d: 0.5429, groups: {'7-8': 'einfach'} },
  { id: 'ogham23', title: 'Ogham', topic: 'Kodierung, Verschlüsselung, Häufigkeit', page: 44, year: 2023, d: 0.5455, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'geburtstag21', title: 'Geburtstagsrätsel', topic: 'Algorithmen, Lösungssuche, rückwärts', page: 30, year: 2021, d: 0.5484, groups: {'5-6': 'schwer', '9-10': 'einfach'} },
  { id: 'helligkeit', title: 'Helligkeitskarte', topic: 'Systeme, Neuronale Netze, Convolutional NN', page: 40, year: 2025, d: 0.5556, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'segelboot24', title: 'Segelboot', topic: 'Modellierung, Graphen, Eulerweg', page: 61, year: 2024, d: 0.5556, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'sechsecke22', title: 'Sechsecke ausmalen', topic: 'Algorithmen, Grundbausteine, Bedingung / Wiederholung', page: 51, year: 2022, d: 0.5625, groups: {'5-6': 'einfach'} },
  { id: 'unterscheidung20', title: 'Unterscheidung', topic: 'Modellierung, Neuronale Netze, Heat Maps', page: 61, year: 2020, d: 0.5714, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'sprachkurse23', title: 'Sprachkurse', topic: 'Modellierung, Graphen, bipartite Graphen', page: 58, year: 2023, d: 0.5758, groups: {'7-8': 'schwer', '11-13': 'einfach'} },
  { id: 'murmelband21', title: 'Murmelband', topic: 'Modellierung, Automaten, Turingmaschine', page: 40, year: 2021, d: 0.5806, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'lefty2', title: 'Lefty 2', topic: 'Systeme, Architektur, Befehlssatz', page: 52, year: 2025, d: 0.5833, groups: {'5-6': 'schwer', '7-8': 'mittel'} },
  { id: 'naechster24', title: 'Der Nächste bitte!', topic: 'Algorithmen, Optimierung, Scheduling', page: 23, year: 2024, d: 0.5833, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'verstecke22', title: 'Verstecke', topic: 'Kodierung, Fehlerkorrektur, Parität', page: 58, year: 2022, d: 0.5938, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'nachrichtennetz20', title: 'Nachrichten-Netz', topic: 'Modellierung, Graphen, Zentrum', page: 38, year: 2020, d: 0.6, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'postfix23', title: 'Postfix-Notation', topic: 'Theorie, Formale Sprachen, Strukturbaum', page: 46, year: 2023, d: 0.6061, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'momos', title: 'Momos Spiel', topic: 'Programmierung, Grundbausteine, Wiederholung', page: 58, year: 2025, d: 0.6111, groups: {'5-6': 'schwer'} },
  { id: 'baumtouren24', title: 'Baumtouren', topic: 'Algorithmen, Sortieren, topologische Sortierung', page: 13, year: 2024, d: 0.6111, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'tische21', title: 'Verflixte Tische', topic: 'Algorithmen, Optimierung, Lineare Programmierung', page: 57, year: 2021, d: 0.6129, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'endstand22', title: 'Endstand', topic: 'Programmieren, Logik, Prolog', page: 23, year: 2022, d: 0.625, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'sturerfred20', title: 'Sturer Fred', topic: 'Programmieren, Grundbausteine, Wiederholung, Invariante', page: 54, year: 2020, d: 0.6286, groups: {'7-8': 'schwer', '9-10': 'mittel'} },
  { id: 'zerobots23', title: 'Zerobots Mission', topic: 'Systeme, Roboter, Planung', page: 64, year: 2023, d: 0.6364, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'bibimbap', title: 'Bibimbap 비빔밥', topic: 'Algorithmen, Optimierung, Scheduling', page: 24, year: 2025, d: 0.6389, groups: {'5-6': 'mittel'} },
  { id: 'sternmobiles24', title: 'Stern-Mobiles', topic: 'Algorithmen, Rekursion', page: 65, year: 2024, d: 0.6389, groups: {'11-13': 'mittel'} },
  { id: 'netze21', title: 'Theklas Netze', topic: 'Modellierung, Graphen, Adjazenzmatrix', page: 53, year: 2021, d: 0.6452, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'rundhangar22', title: 'Rundhangar', topic: 'Algorithmen, Analyse, worst/best/average case', page: 46, year: 2022, d: 0.6562, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'bominos20', title: 'Bominos', topic: 'Modellierung, deklarativ vs operational', page: 19, year: 2020, d: 0.6571, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'lichterstern', title: 'Lichterstern', topic: 'Modellierung, Logik, Operatoren', page: 54, year: 2025, d: 0.6667, groups: {'7-8': 'einfach'} },
  { id: 'umstapeln24', title: 'Umstapeln', topic: 'Algorithmen, Sortieren, topologische Sortierung', page: 69, year: 2024, d: 0.6667, groups: {'11-13': 'schwer'} },
  { id: 'gobots23', title: 'Go-Bots', topic: 'Systeme, Multiagentensystem, Koordination', page: 32, year: 2023, d: 0.6667, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'rettebaum21', title: 'Rette den Baum!', topic: 'Algorithmen, Graphen, minimaler Schnitt', page: 44, year: 2021, d: 0.6774, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'hotspot20', title: 'Hotspot-Heizung', topic: 'Modellierung, Graphen, Dominating Set', page: 30, year: 2020, d: 0.6857, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'kartenquadrat22', title: 'Kartenquadrat', topic: 'Modellierung, Graphen, Rundweg', page: 33, year: 2022, d: 0.6875, groups: {'11-13': 'schwer'} },
  { id: 'drachen', title: 'Der Drachen ist weg!', topic: 'Algorithmen, Lösungssuche, Topologie', page: 33, year: 2025, d: 0.6944, groups: {'7-8': 'schwer'} },
  { id: 'bausteinmaschine224', title: 'Baustein-Maschine 2', topic: 'Algorithmen, Sortieren, in-place', page: 17, year: 2024, d: 0.6944, groups: {'9-10': 'schwer', '11-13': 'schwer'} },
  { id: 'wanderungen23', title: 'Wanderungen', topic: 'Algorithmen, Optimierung, Dynamische Programmierung', page: 60, year: 2023, d: 0.697, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'fruechte21', title: 'Früchte stapeln', topic: 'Prozesse, Reihenfolge, Deadlock', page: 28, year: 2021, d: 0.7097, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'linksrechts20', title: 'Links-Rechts-Spiel', topic: 'Algorithmen, Spiele, Minimax', page: 37, year: 2020, d: 0.7143, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'zauberschule22', title: 'Zauberschule', topic: 'Algorithmen, Graphen, kürzeste Wege', page: 65, year: 2022, d: 0.7188, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'kurierdienst', title: 'Kurierdienst', topic: 'Kodierung, Verschlüsselung, visuelle Kryptografie', page: 48, year: 2025, d: 0.7222, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'ballon224', title: 'Ballon-Maschine 2', topic: 'Programmierung, Grundbausteine, Bedingung', page: 11, year: 2024, d: 0.7222, groups: {'5-6': 'schwer'} },
  { id: 'malerei23', title: 'Rekursive Malerei', topic: 'Modellierung, Rekursion, Abbruchbedingung', page: 48, year: 2023, d: 0.7273, groups: {'11-13': 'schwer'} },
  { id: 'dottis21', title: 'Dottis', topic: 'Modellierung, Datenstrukturen, binärer Suchbaum', page: 19, year: 2021, d: 0.7419, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'bergsteiger20', title: 'Bergsteiger', topic: 'Algorithmen, Greedy, Hill Climbing', page: 13, year: 2020, d: 0.7429, groups: {'5-6': 'einfach'} },
  { id: 'parkplaetze', title: 'Parkplätze', topic: 'Theoretische Informatik, Automaten, Kellerautomaten', page: 64, year: 2025, d: 0.75, groups: {'11-13': 'schwer'} },
  { id: 'happybirthday24', title: 'Happy Birthday', topic: 'Algorithmen, Beschreibung, Programmablaufplan', page: 33, year: 2024, d: 0.75, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'schokolade22', title: 'Schokolade packen', topic: 'Algorithmen, Optimierung, Verpackungsproblem', page: 49, year: 2022, d: 0.75, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'bausteine23', title: 'Biber-Bausteine', topic: 'Modellierung, Datenbanken, Tabellen', page: 13, year: 2023, d: 0.7576, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'turniersieger20', title: 'Turniersieger', topic: 'Algorithmen, Sortieren, Topologische Sortierung', page: 60, year: 2020, d: 0.7714, groups: {'11-13': 'mittel'} },
  { id: 'gruppenarbeit21', title: 'Gruppenarbeit', topic: 'Algorithmen, Graphen, Färbung', page: 32, year: 2021, d: 0.7742, groups: {'11-13': 'schwer'} },
  { id: 'schere', title: 'Schere, Stein, Papier', topic: 'Algorithmen, Analyse, Invarianten', page: 68, year: 2025, d: 0.7778, groups: {'11-13': 'schwer'} },
  { id: 'baelle24', title: 'Bälle', topic: 'Kodierung, Kompression, verlustfrei', page: 7, year: 2024, d: 0.7778, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'fliegenpilz22', title: 'Achtung Fliegenpilz', topic: 'Algorithmen, Regeln', page: 7, year: 2022, d: 0.7812, groups: {'7-8': 'einfach', '9-10': 'einfach'} },
  { id: 'emma23', title: 'Emma erledigt', topic: 'Algorithmen, Graphen, kürzeste Wege', page: 26, year: 2023, d: 0.7879, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'leiterspiel20', title: 'Leiterspiel', topic: 'Algorithmen, Graphen, Kürzeste Wege', page: 36, year: 2020, d: 0.8, groups: {'9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'bergseen', title: 'Bergseen', topic: 'Algorithmen, Graphen-Algorithmen, Flussalgorithmen', page: 15, year: 2025, d: 0.8056, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'schatzkarte24', title: 'Schatzkarte', topic: 'Modellierung, Graph', page: 57, year: 2024, d: 0.8056, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'moeglichstbald21', title: 'Möglichst bald!', topic: 'Algorithmen, Lösungssuche, bidirektional', page: 38, year: 2021, d: 0.8065, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'boeden22', title: 'Bemalte Böden', topic: 'Algorithmen, Geometrie, Voronoi-Regionen', page: 11, year: 2022, d: 0.8125, groups: {'11-13': 'schwer'} },
  { id: 'ziffernschloss23', title: 'Ziffernschloss', topic: 'Algorithmen, Kombinatorik, Permutation', page: 67, year: 2023, d: 0.8182, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'tunnel20', title: 'Durch den Tunnel', topic: 'Algorithmen, Planung', page: 25, year: 2020, d: 0.8286, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'adresse', title: 'Adress-Erkennung', topic: 'Theoretische Informatik, Automaten, Endliche Automaten', page: 7, year: 2025, d: 0.8333, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'pip24', title: 'Pip der Pirat', topic: 'Algorithmen, Lösungssuche, binäre Suche', page: 45, year: 2024, d: 0.8333, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'koko21', title: 'Der Affe Koko', topic: 'Modellierung, Graphen, Komponenten', page: 17, year: 2021, d: 0.8387, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'edelsteine22', title: 'Edelsteine', topic: 'Algorithmen, Analyse, Verallgemeinerung', page: 22, year: 2022, d: 0.8438, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'burgenbau23', title: 'Burgenbau', topic: 'Algorithmen, Optimierung, Scheduling', page: 21, year: 2023, d: 0.8485, groups: {'9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'parcours20', title: 'Biber-Parcours', topic: 'Algorithmen, Optimierung, Backtracking', page: 14, year: 2020, d: 0.8571, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'schwarzweiss', title: 'Schwarz – Weiß', topic: 'Kodierung, Komprimierung', page: 70, year: 2025, d: 0.8611, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'erkundung24', title: 'Erkundung', topic: 'Algorithmen, Lösungssuche, Tiefensuche', page: 25, year: 2024, d: 0.8611, groups: {'11-13': 'schwer'} },
  { id: 'baumstaemme21', title: 'Baumstämme', topic: 'Algorithmen, Sortieren, Komplexität', page: 8, year: 2021, d: 0.871, groups: {'11-13': 'schwer'} },
  { id: 'strand22', title: 'Spiel am Strand', topic: 'Algorithmen, Spiele, Spielbaum; Spieltheorie', page: 52, year: 2022, d: 0.875, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'zerteilen23', title: 'Zerteile den Code', topic: 'Kodierung, Theorie, Präfixcode', page: 66, year: 2023, d: 0.8788, groups: {'11-13': 'schwer'} },
  { id: 'pruefbiber20', title: 'Prüf-Biber', topic: 'Kodierung, Fehlerkorrektur, Hamming Code', page: 44, year: 2020, d: 0.8857, groups: {'11-13': 'schwer'} },
  { id: 'pruefbiber', title: 'Prüf-Biber', topic: 'Kodierung, Fehlerkorrektur, Hamming-Code', page: 66, year: 2025, d: 0.8889, groups: {'11-13': 'schwer'} },
  { id: 'frowny24', title: 'Frowny', topic: 'Algorithmen, Spiele, Spielbaum', page: 29, year: 2024, d: 0.8889, groups: {'11-13': 'schwer'} },
  { id: 'clans21', title: 'Clans von Beavaria', topic: 'Algorithmen, Optimierung, Greedy', page: 15, year: 2021, d: 0.9032, groups: {'11-13': 'schwer'} },
  { id: 'filmabend22', title: 'Filmabend', topic: 'Algorithmen, Analyse, Laufzeit', page: 27, year: 2022, d: 0.9062, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'konflikt23', title: 'Konflikt-Detektor', topic: 'Modellierung, Neuronale Netze, Perzeptron', page: 37, year: 2023, d: 0.9091, groups: {'11-13': 'schwer'} },
  { id: 'flaggenbilder20', title: 'Flaggenbilder', topic: 'Kodierung, Kompression, Bildkompression', page: 27, year: 2020, d: 0.9143, groups: {'11-13': 'schwer'} },
  { id: 'theater', title: 'Zum Theater!', topic: 'Algorithmen, Optimierung, Dynamische Programmierung', page: 80, year: 2025, d: 0.9167, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'verschluesseln24', title: 'Bilder verschlüsseln', topic: 'Kodierung, Verschlüsselung, Grundlagen', page: 21, year: 2024, d: 0.9167, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'nasenlaenge21', title: 'Nasenlänge', topic: 'Programmieren, Grundbausteine, Wiederholung / Variablen', page: 42, year: 2021, d: 0.9355, groups: {'11-13': 'schwer'} },
  { id: 'zauberland22', title: 'Zauberland', topic: 'Theorie, formale Sprachen, kontextfreie Grammatiken', page: 63, year: 2022, d: 0.9375, groups: {'11-13': 'schwer'} },
  { id: 'domino23', title: 'Domino', topic: 'Modellierung, Graphen, Eulerweg', page: 23, year: 2023, d: 0.9394, groups: {'11-13': 'schwer'} },
  { id: 'zahlenmaschine20', title: 'Zahlenmaschine', topic: 'Programmieren, Rekursion vs Iteration', page: 63, year: 2020, d: 0.9429, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'klausuren', title: 'Klausurenplan', topic: 'Modellierung, Graphen, Färbung', page: 46, year: 2025, d: 0.9444, groups: {'11-13': 'schwer'} },
  { id: 'wortketten24', title: 'Wortketten', topic: 'Modellierung, Graphen, Komponenten', page: 72, year: 2024, d: 0.9444, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'biberarbeit21', title: 'Biber-Arbeit', topic: 'Algorithmen, Optimierung, Scheduling', page: 10, year: 2021, d: 0.9677, groups: {'11-13': 'schwer'} },
  { id: 'meisterschaft22', title: 'Bibermeisterschaft', topic: 'Algorithmen, Lösungssuche, Rückwärtssuche', page: 15, year: 2022, d: 0.9688, groups: {'11-13': 'schwer'} },
  { id: 'anprobe23', title: 'Anprobe', topic: 'Algorithmen, Suchen, Binäre Suche', page: 8, year: 2023, d: 0.9697, groups: {'11-13': 'schwer'} },
  { id: 'neueshaus20', title: 'Neues Haus', topic: 'Algorithmen, Klassifikation, k nächste Nachbarn', page: 39, year: 2020, d: 0.9714, groups: {'7-8': 'schwer', '11-13': 'einfach'} },
  { id: 'biberone', title: 'Biberone', topic: 'Modellierung, Logik, XOR', page: 21, year: 2025, d: 0.9722, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'buchstaben24', title: 'Gleiche Buchstaben', topic: 'Algorithmen, Lösungssuche', page: 31, year: 2024, d: 0.9722, groups: {'9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'biberjones', title: 'Biber Jones', topic: 'Algorithmen, Optimierung, Pareto-Optimum', page: 17, year: 2025, d: 1, groups: {'11-13': 'schwer'} },
  { id: 'kartendrehen24', title: 'Karten drehen', topic: 'Kodierung, Binärzahlen, binäres Zählen', page: 37, year: 2024, d: 1, groups: {'11-13': 'schwer'} },
  { id: 'bruecken23', title: 'Brücken bauen!', topic: 'Modellierung, Graphen, gewichteter Graph', page: 17, year: 2023, d: 1, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'computerviren22', title: 'Computerviren', topic: 'Systeme, Netzwerke, Malware', page: 20, year: 2022, d: 1.0, groups: {'11-13': 'schwer'} },
  { id: 'sosberge21', title: 'SOS aus den Bergen', topic: 'Systeme, Netzwerke, Redundanz', page: 48, year: 2021, d: 1.0, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'rueckseite20', title: 'Rückseite', topic: 'Modellierung, Logik, Implikation', page: 47, year: 2020, d: 1, groups: {'11-13': 'schwer'} }
];

/* Punkteschema nach Bebras-Standard (im Heft nicht angegeben):
   richtig = Pluspunkte, falsch = Abzug, keine Antwort = 0. */
window.BIBER_SCORING = {
  einfach: { right: 6, wrong: -2 },
  mittel: { right: 9, wrong: -3 },
  schwer: { right: 12, wrong: -4 }
};
