/* Aufgabenliste: Informatik-Biber 2025 (alle 37 Aufgaben) und ausgewaehlte Aufgaben der Hefte 2020-2024.
   Jede Aufgabe hat Thema, Heftjahr, Heftseite und ihre Schwierigkeit laut Heft je Altersgruppe
   (Klassenstufen 3-4, 5-6, 7-8, 9-10, 11-13).
   d (0..1) ist die relative Position in der Aufgabenliste ihres Heftes (Seite 6: nach ungefaehr steigender
   Schwierigkeit): 0 = leichteste, 1 = schwerste Aufgabe des Heftes. Die Liste hier ist nach d sortiert und bildet die
   gemeinsame Schwierigkeitsskala fuer das adaptive Training. */
window.BIBER_TASKS = [
  { id: 'fingerfarben', title: 'Fingerfarben', topic: 'Systeme, Neuronale Netze, Diffusionsmodell', page: 37, year: 2025, d: 0.0, groups: {'3-4': 'einfach'} },
  { id: 'flugzeuge', title: 'Flugzeuge', topic: 'Algorithmen, Optimierung, Scheduling', page: 38, year: 2025, d: 0.0278, groups: {'3-4': 'einfach', '5-6': 'einfach'} },
  { id: 'hivobu', title: 'Hivobu', topic: 'Programmierung, Syntax, Postfix-Notation', page: 42, year: 2025, d: 0.0556, groups: {'3-4': 'schwer', '5-6': 'einfach'} },
  { id: 'impark24', title: 'Im Park', topic: 'Modellierung, Datenstrukturen, Stack', page: 35, year: 2024, d: 0.0556, groups: {'3-4': 'einfach'} },
  { id: 'bauklotze1', title: 'Bauklötze 1', topic: 'Programmierung, Grundbausteine, Sequenz', page: 9, year: 2025, d: 0.0833, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'buntestrasse20', title: 'Bunte Straße', topic: 'Modellierung, Graphen, Färbung', page: 21, year: 2020, d: 0.0857, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'blumenstrauss23', title: 'Blumenstrauß', topic: 'Modellierung, Algorithmen, Programmablaufplan', page: 15, year: 2023, d: 0.0909, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'burger22', title: 'Biber-Burger', topic: 'Algorithmen, Lösungssuche, Constraint Satisfaction', page: 13, year: 2022, d: 0.0938, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'obstkoerbe', title: 'Obstkörbe', topic: 'Algorithmen, Sortieren, Ordnung', page: 62, year: 2025, d: 0.1111, groups: {'3-4': 'einfach'} },
  { id: 'bruecken21', title: 'Brückenbau', topic: 'Modellierung, Mathematik, Mengen', page: 12, year: 2021, d: 0.129, groups: {'3-4': 'einfach', '5-6': 'einfach'} },
  { id: 'nachhause', title: 'Nach Hause', topic: 'Algorithmus, Analyse, Bias', page: 60, year: 2025, d: 0.1389, groups: {'3-4': 'mittel', '5-6': 'einfach'} },
  { id: 'amschwersten20', title: 'Am schwersten', topic: 'Algorithmen, Sortieren, Topologische Sortierung', page: 7, year: 2020, d: 0.1429, groups: {'3-4': 'schwer', '5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'bauklotze2', title: 'Bauklötze 2', topic: 'Algorithmen, Eigenschaften, wohldefiniert', page: 11, year: 2025, d: 0.1667, groups: {'7-8': 'einfach'} },
  { id: 'ineinemzug20', title: 'In einem Zug', topic: 'Algorithmen, Graphen, Eulerscher Pfad', page: 34, year: 2020, d: 0.1714, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'tagnebel', title: 'Tag im Nebel', topic: 'Algorithmen, Computergrafik, Floodfill Algorithmus', page: 74, year: 2025, d: 0.1944, groups: {'7-8': 'einfach', '9-10': 'einfach'} },
  { id: 'muttern22', title: 'Muttern und Schrauben', topic: 'Modellierung, Automaten, Kellerautomat', page: 42, year: 2022, d: 0.2188, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'zahlenmaschine', title: 'Zahlenmaschine', topic: 'Algorithmen, Sortieren, Sortiernetzwerk', page: 78, year: 2025, d: 0.2222, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'berukone24', title: 'Berukone', topic: 'Algorithmen, Lösungssuche, Backtracking', page: 19, year: 2024, d: 0.2222, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'seerosen21', title: 'Seerosen-Treff', topic: 'Algorithmen, Lösungssuche, Breiten- und Tiefensuche', page: 47, year: 2021, d: 0.2258, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'blaetter', title: 'Blätter im Wind', topic: 'Algorithmen, Klassifikation, Entscheidungsbaum', page: 26, year: 2025, d: 0.25, groups: {'7-8': 'einfach'} },
  { id: 'lampe', title: 'Verrückte Lampe', topic: 'Modellierung, Logik, Operatoren', page: 76, year: 2025, d: 0.2778, groups: {'3-4': 'schwer', '5-6': 'mittel'} },
  { id: 'achteck22', title: 'Geheimes Achteck', topic: 'Kodierung, Verschlüsselung', page: 29, year: 2022, d: 0.2812, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'lefty1', title: 'Lefty 1', topic: 'Systeme, Architektur, Befehlssatz', page: 50, year: 2025, d: 0.3056, groups: {'3-4': 'mittel'} },
  { id: 'erdbeerklau21', title: 'Erdbeerklau', topic: 'Modellierung, Graphen, Cliquen', page: 23, year: 2021, d: 0.3226, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'biberholz', title: 'Biberholz', topic: 'Modellierung, Datenbanken, Abfragen', page: 19, year: 2025, d: 0.3333, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'schatzsuche23', title: 'Schatzsuche', topic: 'Modellierung, Distanzen, Manhattan-Distanz', page: 54, year: 2023, d: 0.3333, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'holz', title: 'Holz für den Damm', topic: 'Algorithmen, Optimierung, Teilfolge', page: 44, year: 2025, d: 0.3611, groups: {'3-4': 'schwer', '5-6': 'mittel'} },
  { id: 'nimm20', title: 'Nim(m)', topic: 'Algorithmen, Spiele, Nim', page: 41, year: 2020, d: 0.3714, groups: {'9-10': 'schwer', '11-13': 'schwer'} },
  { id: 'fiatlux22', title: 'Fiat Lux', topic: 'Systeme, Schaltungen, Logik-Bausteine', page: 25, year: 2022, d: 0.375, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'kerzen', title: 'Brennende Kerzen', topic: 'Algorithmen, Analyse, Verifikation', page: 31, year: 2025, d: 0.3889, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'mehltransport', title: 'Mehltransport', topic: 'Algorithmen, Optimierung, Scheduling', page: 56, year: 2025, d: 0.4167, groups: {'9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'ueberblick21', title: 'Überblick', topic: 'Algorithmen, Graphen, minimale Knotenüberdeckung', page: 55, year: 2021, d: 0.4194, groups: {'5-6': 'schwer', '7-8': 'mittel'} },
  { id: 'zugentladen23', title: 'Zug entladen', topic: 'Algorithmen, Sortieren, Inversion', page: 69, year: 2023, d: 0.4242, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'stammbaum', title: 'Stammbaum', topic: 'Modellierung, Mathematik, Funktionen', page: 72, year: 2025, d: 0.4444, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'gemuesebeet23', title: 'Gemüsebeet', topic: 'Algorithmen, Lösungssuche, Backtracking', page: 30, year: 2023, d: 0.4545, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'passwoerter20', title: 'Passwörter', topic: 'Modellierung, Automaten, DEA', page: 42, year: 2020, d: 0.4571, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'blumentoepfe', title: 'Blumentöpfe', topic: 'Algorithmen, Lösungssuche, Bottom-Up', page: 29, year: 2025, d: 0.4722, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'gnomesort24', title: 'Baustein-Maschine 1', topic: 'Algorithmen, Sortieren, Gnomesort', page: 15, year: 2024, d: 0.4722, groups: {'7-8': 'schwer'} },
  { id: 'bebrasien', title: 'Bebrasien', topic: 'Modellierung, Graphen', page: 13, year: 2025, d: 0.5, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'superbebras24', title: 'Superbebras', topic: 'Theoretische Informatik, Automaten, DEA', page: 67, year: 2024, d: 0.5, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'teppich22', title: 'Teppichmuster', topic: 'Programmieren / Algorithmen, Grundbausteine, Bedingung', page: 56, year: 2022, d: 0.5, groups: {'5-6': 'schwer', '7-8': 'mittel'} },
  { id: 'sierpinski20', title: 'Sierpinski-Dreieck', topic: 'Modellierung, Rekursion, Fraktale', page: 52, year: 2020, d: 0.5143, groups: {'9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'martinasdorf23', title: 'Martinas Dorf', topic: 'Modellierung, Graphen, Spannbaum', page: 39, year: 2023, d: 0.5152, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'seoul', title: 'Entdecke Seoul!', topic: 'Algorithmen, Graphen-Algorithmen, Tiefensuche', page: 35, year: 2025, d: 0.5278, groups: {'7-8': 'schwer'} },
  { id: 'ogham23', title: 'Ogham', topic: 'Kodierung, Verschlüsselung, Häufigkeit', page: 44, year: 2023, d: 0.5455, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'helligkeit', title: 'Helligkeitskarte', topic: 'Systeme, Neuronale Netze, Convolutional NN', page: 40, year: 2025, d: 0.5556, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'murmelband21', title: 'Murmelband', topic: 'Modellierung, Automaten, Turingmaschine', page: 40, year: 2021, d: 0.5806, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'lefty2', title: 'Lefty 2', topic: 'Systeme, Architektur, Befehlssatz', page: 52, year: 2025, d: 0.5833, groups: {'5-6': 'schwer', '7-8': 'mittel'} },
  { id: 'naechster24', title: 'Der Nächste bitte!', topic: 'Algorithmen, Optimierung, Scheduling', page: 23, year: 2024, d: 0.5833, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'verstecke22', title: 'Verstecke', topic: 'Kodierung, Fehlerkorrektur, Parität', page: 58, year: 2022, d: 0.5938, groups: {'5-6': 'mittel', '7-8': 'einfach'} },
  { id: 'momos', title: 'Momos Spiel', topic: 'Programmierung, Grundbausteine, Wiederholung', page: 58, year: 2025, d: 0.6111, groups: {'5-6': 'schwer'} },
  { id: 'bibimbap', title: 'Bibimbap 비빔밥', topic: 'Algorithmen, Optimierung, Scheduling', page: 24, year: 2025, d: 0.6389, groups: {'5-6': 'mittel'} },
  { id: 'sternmobiles24', title: 'Stern-Mobiles', topic: 'Algorithmen, Rekursion', page: 65, year: 2024, d: 0.6389, groups: {'11-13': 'mittel'} },
  { id: 'lichterstern', title: 'Lichterstern', topic: 'Modellierung, Logik, Operatoren', page: 54, year: 2025, d: 0.6667, groups: {'7-8': 'einfach'} },
  { id: 'rettebaum21', title: 'Rette den Baum!', topic: 'Algorithmen, Graphen, minimaler Schnitt', page: 44, year: 2021, d: 0.6774, groups: {'7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'drachen', title: 'Der Drachen ist weg!', topic: 'Algorithmen, Lösungssuche, Topologie', page: 33, year: 2025, d: 0.6944, groups: {'7-8': 'schwer'} },
  { id: 'wanderungen23', title: 'Wanderungen', topic: 'Algorithmen, Optimierung, Dynamische Programmierung', page: 60, year: 2023, d: 0.697, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'fruechte21', title: 'Früchte stapeln', topic: 'Prozesse, Reihenfolge, Deadlock', page: 28, year: 2021, d: 0.7097, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'zauberschule22', title: 'Zauberschule', topic: 'Algorithmen, Graphen, kürzeste Wege', page: 65, year: 2022, d: 0.7188, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'kurierdienst', title: 'Kurierdienst', topic: 'Kodierung, Verschlüsselung, visuelle Kryptografie', page: 48, year: 2025, d: 0.7222, groups: {'7-8': 'schwer', '9-10': 'mittel', '11-13': 'einfach'} },
  { id: 'dottis21', title: 'Dottis', topic: 'Modellierung, Datenstrukturen, binärer Suchbaum', page: 19, year: 2021, d: 0.7419, groups: {'5-6': 'schwer', '7-8': 'mittel', '9-10': 'einfach'} },
  { id: 'parkplaetze', title: 'Parkplätze', topic: 'Theoretische Informatik, Automaten, Kellerautomaten', page: 64, year: 2025, d: 0.75, groups: {'11-13': 'schwer'} },
  { id: 'schere', title: 'Schere, Stein, Papier', topic: 'Algorithmen, Analyse, Invarianten', page: 68, year: 2025, d: 0.7778, groups: {'11-13': 'schwer'} },
  { id: 'bergseen', title: 'Bergseen', topic: 'Algorithmen, Graphen-Algorithmen, Flussalgorithmen', page: 15, year: 2025, d: 0.8056, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'tunnel20', title: 'Durch den Tunnel', topic: 'Algorithmen, Planung', page: 25, year: 2020, d: 0.8286, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'adresse', title: 'Adress-Erkennung', topic: 'Theoretische Informatik, Automaten, Endliche Automaten', page: 7, year: 2025, d: 0.8333, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'parcours20', title: 'Biber-Parcours', topic: 'Algorithmen, Optimierung, Backtracking', page: 14, year: 2020, d: 0.8571, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'schwarzweiss', title: 'Schwarz – Weiß', topic: 'Kodierung, Komprimierung', page: 70, year: 2025, d: 0.8611, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'strand22', title: 'Spiel am Strand', topic: 'Algorithmen, Spiele, Spielbaum; Spieltheorie', page: 52, year: 2022, d: 0.875, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'pruefbiber', title: 'Prüf-Biber', topic: 'Kodierung, Fehlerkorrektur, Hamming-Code', page: 66, year: 2025, d: 0.8889, groups: {'11-13': 'schwer'} },
  { id: 'frowny24', title: 'Frowny', topic: 'Algorithmen, Spiele, Spielbaum', page: 29, year: 2024, d: 0.8889, groups: {'11-13': 'schwer'} },
  { id: 'theater', title: 'Zum Theater!', topic: 'Algorithmen, Optimierung, Dynamische Programmierung', page: 80, year: 2025, d: 0.9167, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'klausuren', title: 'Klausurenplan', topic: 'Modellierung, Graphen, Färbung', page: 46, year: 2025, d: 0.9444, groups: {'11-13': 'schwer'} },
  { id: 'biberone', title: 'Biberone', topic: 'Modellierung, Logik, XOR', page: 21, year: 2025, d: 0.9722, groups: {'9-10': 'schwer', '11-13': 'mittel'} },
  { id: 'biberjones', title: 'Biber Jones', topic: 'Algorithmen, Optimierung, Pareto-Optimum', page: 17, year: 2025, d: 1.0, groups: {'11-13': 'schwer'} },
  { id: 'kartendrehen24', title: 'Karten drehen', topic: 'Kodierung, Binärzahlen, binäres Zählen', page: 37, year: 2024, d: 1.0, groups: {'11-13': 'schwer'} },
  { id: 'bruecken23', title: 'Brücken bauen!', topic: 'Modellierung, Graphen, gewichteter Graph', page: 17, year: 2023, d: 1.0, groups: {'9-10': 'schwer', '11-13': 'mittel'} }
];

/* Punkteschema nach Bebras-Standard (im Heft nicht angegeben):
   richtig = Pluspunkte, falsch = Abzug, keine Antwort = 0. */
window.BIBER_SCORING = {
  einfach: { right: 6, wrong: -2 },
  mittel: { right: 9, wrong: -3 },
  schwer: { right: 12, wrong: -4 }
};
